### ISSUE TITLE
Backward compatibility & doc

### ISSUE THREAD

**Issue by tilap** [christophehurpeau/nightingale#3]
Before, `nightingale` exports `Levels`. It seems it changes over time to `levels`.

➡️ Documentation need to be updated.
➡️ What about backward compatibility ?

**Comment by christophehurpeau** [comment]
before v4, it exported `LogLevels`. During v4 (2016), it was exported to another package, and renamed to `levels`, stayed the same since, if I'm not mistaken.
- Documentation need to be updated: yes ! `Levels` seems to be used in every readme, I will fix that
- before v5, changes were frequent and not well documented sorry !

**Comment by christophehurpeau** [comment]
It is also exported as `Level`, probably for backward compatibility :)
